# See http://www.appveyor.com/docs/appveyor-yml for many more options

#Publish to PowerShell Gallery with this key
environment:
  NuGetApiKey:
    secure: AZ37p+H63dtSWUV6jbQg6s8PDNEDpF8ApLFqwc665zRy4dgUdCA5lVkawzaIHUnr

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

build: false

# to run your custom scripts instead of provider deployments
deploy_script:
  - ps: . .\Build\deploy.ps1